### ISSUE TITLE
Add UML diagrams

### ISSUE THREAD

**Issue by danvanhorn** [cs361fall2017/team21#76]
### UML Class Diagram (+10%)
- Add a UML class diagram to the wiki pages on the team repo which illustrates the final state of the code contained within your team's repo at the end of Sprint 4. This diagram must demonstrate correct UML structure and notation, and be consistent with your implementation.
### UML Sequence Diagram (+10%) 
- Add a UML sequence diagram to the wiki pages on the team repo which illustrates the final state of the code contained within your team's repo at the end of Sprint 4. This diagram must demonstrate correct UML structure and notation, illustrate both versions of the AcesUp game, and be consistent with your implementation.

**Comment by cashd932** [comment]
Diagrams drawn and added to a new page called [Sprint 4 UML Diagrams](https://github.com/cs361fall2017/team21/wiki/Sprint-4-UML-Diagrams)
